### ISSUE TITLE
Unkown test name and test class when screenshot is taken from espresso view action

### ISSUE THREAD

**Issue by tusharkathuria** [Karumi/Shot#159] opened 2020-10-13 08:47 UTC
### Expected behaviour
There should be a way to give custom test name and test class for report if it can't be detected by library

### Actual behaviour
In the html report generated test name test class are unknown:
<img width="232" alt="Screenshot 2020-10-13 at 2 14 28 PM" src="https://user-images.githubusercontent.com/10515849/95837629-6c4cee00-0d5e-11eb-8e40-f94532bee9bf.png">

### Steps to reproduce
In order to take screenshot of a view in activity, I invoke the `compareScreenshot` method from espresso ViewAction as follows:
```kotlin
fun takeScreenshot(name: String): ViewAction {
    return object: ViewAction {
        override fun getDescription(): String {
            return "Takes screenshot of view"
        }

        override fun getConstraints(): Matcher<View> {
            return CoreMatchers.allOf(ViewMatchers.isDisplayed(), ViewMatchers.isAssignableFrom(View::class.java))
        }

        override fun perform(uiController: UiController?, view: View) {
            compareScreenshot(view, name = name)
        }
    }
```

and then I use this ViewAction from test class extending `ScreenshotTest` as follows:
```kotlin
@Test
fun testScreenshotExpanded() {
    val interaction = onView(ViewMatchers.withId(VIEW_ID))
    interaction.perform(takeScreenshot("view"))
}
```

### Version of the library
`com.karumi:shot:5.1.2`

Am I missing anything here? If not, is there any work around that I can use

**Comment by tusharkathuria** [comment] 2020-10-29 05:59
Hi, Any update on this? 
Let me know if more details are needed from my side

**Comment by Cotel** [comment] 2020-10-30 11:54
I'm having the same behavior without any espresso usage. In fact, only one screenshot is recorded as they override with the same file name.

I'm mounting a fragment on a ActivityScenario and running `compareScreenshot(fragment)` inside a lambda executed once the activity and fragment are ready and visible.

**Comment by tusharkathuria** [comment] 2020-11-03 05:37
Yeah. Looks like library tries to infer test class and name based on call stack. In the cases where compare screenshot is invoked from separate thread, it can't infer it which is expected. I am only looking for a way to give custom test class and test name in this case. @pedrovgs , Can you help here?

**Comment by pedrovgs** [comment] 2020-11-09 07:24
Hi @tusharkathuria @Cotel sorry for the late response. As @tusharkathuria mentioned, Shot infers the test name and class name based on the stack. That's why Shot can't be used from the target application thread. I'm afraid even if you can configure the name from the public API it will not work due to a bug in a library we use under the hood. I'm closing this issue because we will not be able to fix this issue. As a workaround, you can take the screenshot from the instrumentation test thread as you can see in all the examples provided.

**Closed by pedrovgs** 2020-11-09 07:24 UTC

**Comment by tusharkathuria** [comment] 2020-11-10 13:36
> Hi @tusharkathuria @Cotel sorry for the late response. As @tusharkathuria mentioned, Shot infers the test name and class name based on the stack. That's why Shot can't be used from the target application thread. I'm afraid even if you can configure the name from the public API it will not work due to a bug in a library we use under the hood. I'm closing this issue because we will not be able to fix this issue. As a workaround, you can take the screenshot from the instrumentation test thread as you can see in all the examples provided.

Thanks for responding @pedrovgs . Do you mind sharing link to library that we use under the hood. I can check if the issue is reported there and know about its status

**Comment by pedrovgs** [comment] 2020-11-16 10:33
Sure! https://github.com/facebook/screenshot-tests-for-android

**Comment by jakubvimn** [comment] 2020-11-23 13:09
I think that the Facebook library works fine and the problem is with the Shot API
```
    private fun takeViewSnapshot(name: String?, view: View) {
        val testName = name ?: TestNameDetector.getTestName()
        val snapshotName = "${TestNameDetector.getTestClass()}_$testName"
        try {
            Screenshot
                    .snap(view)
                    .setIncludeAccessibilityInfo(false)
                    .setName(snapshotName)
                    .record()
        } catch (t: Throwable) {
            Log.e("Shot", "Exception captured while taking screenshot for snapshot with name $snapshotName", t)
        }
    }
```

The method from Facebook `Screenshot.setName()` works fine. The only problem is that the snapshotName can't be provided. We can only provide the test name but the class name is always taken from the stack trace.

**Comment by mitsest** [comment] 2021-03-03 13:16
So, will you accept a pull request to add the ability to have custom snapshotName(the same way it is for testName)? @pedrovgs

**Comment by tobiasKaminsky** [comment] 2021-03-04 07:38
` Screenshot.snapActivity(sut).setName(createName()).record();`

You can already do this.

Create name is in my case:
```
private String createName(String prefix) {
        String name = TestNameDetector.getTestClass() + "_" + TestNameDetector.getTestName();

        if (!TextUtils.isEmpty(prefix)) {
            name = name + "_" + prefix;
        }

        if (!DARK_MODE.isEmpty()) {
            name = name + "_" + DARK_MODE;
        }

        if (!COLOR.isEmpty()) {
            name = name + "_" + COLOR;
        }

        return name;
    }

```
 So basically it takes the same class_name approach, but adds color and dark mode if needed.
Resulting in correct names for tests in overview, recorded screenshots, etc.

**Comment by pedrovgs** [comment] 2021-03-04 09:49
Can't you use @tobiasKaminsky approach @mitsest ?

**Comment by mitsest** [comment] 2021-03-04 10:22
I 'm using https://gist.github.com/zawadz88/f057c70d3061454207ccd56e0add81c6 to launch activities.

Could you give more info on how to use Screenshot.snapActivity(sut) ?

@tobiasKaminsky

**Comment by mitsest** [comment] 2021-03-11 12:12
Hello, sorry for coming back to this but I would like to have meaningful names for my screenshots.
I 'm scrolling a recycler and taking screenshots.

This gives both unknown class names, as well as unknown test name. What should I do here?

@tobiasKaminsky @pedrovgs 

```kotlin

fun ScreenshotTest.scrollAndCompareScreenshot(view: RecyclerView, scrollTo: Int = 0, steps: Int? = null, namePrefix: String) {
    val compare = steps?.compareTo(0)
    if (compare != null && compare <= 0) {
        return
    }

    val layoutManager = view.layoutManager as LinearLayoutManager
    view.post { layoutManager.scrollToPositionWithOffset(scrollTo, 0) }
    view.post {
        compareScreenshot(view, name = "${namePrefix}_s_$scrollTo") }
    view.post {
        val firstHiddenItem = layoutManager.findLastCompletelyVisibleItemPosition() + 1
        if (firstHiddenItem < view.adapter?.itemCount ?: 0) {
            scrollAndCompareScreenshot(view, firstHiddenItem, steps?.minus(1), namePrefix)
        }
    }
}

```

**Comment by pedrovgs** [comment] 2021-03-12 09:04
@mitsest take a look at this: https://github.com/Karumi/Shot/#activityscenario-support, it's a similar issue. You can't use view.post because the method ``compareScreenshot`` is going to infer the test name and the class name from the testing apk process. If you move the screenshot comparison to the production apk process the stack is missing and we can't find the test name :(

**Comment by mitsest** [comment] 2021-03-12 11:08
@pedrovgs thanks for the fast replies!
The weird thing here is that I explicitly call compareScreenshot with a name argument, so testName inside takeViewSnapshot is correctly set. We can verify this with the debugger and the .png filenames are correct. There is the issue of the html, though that displays both of them as unkown.

![Screenshot at 2021-03-12 12-04-39](https://user-images.githubusercontent.com/2116434/110932293-91548580-832b-11eb-83da-c7d2cd4524f9.png)

![Screenshot at 2021-03-12 12-04-20](https://user-images.githubusercontent.com/2116434/110932309-99142a00-832b-11eb-8cd7-50b448f8e4d6.png)

**Comment by pedrovgs** [comment] 2021-03-12 14:06
I'm afraid it is something we can't fix because we depend on a different library where we have no access to the name.

**Comment by tusharkathuria** [comment] 2021-03-30 10:43
@pedrovgs I assume that html report generation is handled by Shot and not by Facebook's library. So there must be a way to expose a function to set the custom name to be used in report. 

Major benefit of using facebook's library is that it gives a way to take a screenshot of a view (not just whole activity). In order to achieve that from Espresso, we have to use ViewActions as Espresso prevents direct access to views. And view actions are invoked from a separate thread. So this is a major use case and if fixed, will be helpful to many users of Shot

**Comment by pedrovgs** [comment] 2021-03-30 10:45
We generate the report but the metadata facebook's library generates doesn't let us configure the name and this is the key. We could potentially save the names and try to find what's the equivalent when reading metadata...but it is harder than taking the screenshot from the instrumentation thread.

**Comment by xyzwilliamxyz** [comment] 2021-08-14 01:59
Just for the record in case someone else stumbles upon this thread. Documentation on readme is outdated, but now shot has a utility extension function that helps with this. Now we can do it this way:

`compareScreenshot(scenario.waitForActivity())`

**Comment by milos-kojadinovic** [comment] 2023-01-31 10:19
For compose I find this "util" functions really bad, and not configurable. I suggest not using them, at least until someone fix them. Instead, copy code from them, and remove what is unnecessary. For example I copied :

`      val composeScreenshot = ComposeScreenshotRunner.composeScreenshot
        if (composeScreenshot != null) {
            composeScreenshot.saveScreenshot(node, data)
        } else {
            throw IllegalStateException("Shot couldn't take the screenshot. Ensure your project uses ShotTestRunner as your instrumentation test runner.")
        }`

from `fun compareScreenshot(node: SemanticsNodeInteraction, name: String? = null)`

And then created ScreenshotMetaadata object:
`        val screenshotMetadata = ScreenshotMetadata(
            name = testName,
            testClassName = SomeTest::class.java.name,
            testName = testName
        )`

And then, it work as it should.

**Comment by hidayatrzayev** [comment] 2026-03-18 17:49
I faced this issue when using parameterized screenshot tests. For parameterization I am using [JUnitParams library](https://github.com/Pragmatists/JUnitParams). Had the similar issue that the generated screenshots had the "unknown_" prefix. This is because JUnitParams modifies the method signature by adding parameters into the test function, but Facebook screenshot library assumes that a test method will have no parameters, so it throws on the following invocation

<img width="1041" height="482" alt="Image" src="https://github.com/user-attachments/assets/137236d7-04e8-46e8-a626-45a9f0c7ccb0" />

But I also assume that it mangles the actual test class name, so it appears differently in the stack trace, because `Class.forName` was also throwing. I didn't check that in detail though.

I implemented a fix for this in my  own setup by overriding `compareScreenshot` function and inferring the test name by trying to find the calling method from the stack trace among the declared test methods in the calling class, using reflection.
```kt
override fun compareScreenshot(
    node: SemanticsNodeInteraction,
    name: String?,
) {
    val testClass = this.javaClass
    val className = testClass.simpleName

    val testMethodName = testClass.getCallingTestMethodName()

    disableFlakyComponentsAndWaitForIdle()
    val testName = name ?: testMethodName ?: className
    val testClassName = testClass.name
    val screenshotName = "${testClassName}_$testName"
    val data = ScreenshotMetadata(name = screenshotName, testClassName = testClassName, testName = testName)
    val composeScreenshot = ComposeScreenshotRunner.composeScreenshot
    if (composeScreenshot != null) {
        composeScreenshot.saveScreenshot(node, data)
    } else {
        throw IllegalStateException(
            "Shot couldn't take the screenshot. Ensure your project uses ShotTestRunner as your instrumentation test runner."
        )
    }
}

private fun Class<BaseScreenshotTest>.getCallingTestMethodName(): String? {
    val testMethodNames = declaredMethods
        .filter { it.isAnnotationPresent(Test::class.java) }
        .map { it.name }
        .toSet()

    return Thread.currentThread().stackTrace
        .firstOrNull { it.methodName in testMethodNames }
        ?.methodName
}
```
Not sure if this would work in case a screenshot is taken from espresso, but it works for parameterized tests.
I basically added this into my own `BaseScreenshotTest` class, which inherits from `ScreenshotTest`. 
@pedrovgs would you consider this as a potential fix or do you absolutely have to rely on the Facebook library for that?
