### ISSUE TITLE
NullPointerException when there are no screenshot tests

### ISSUE THREAD

**Issue by AndrewReitz** [Karumi/Shot#188] opened 2021-01-22 19:08 UTC
I'm running the plugin like the documentation says, and am getting this exception. I'm following it through and it looks like the plugin is trying to get screen shots for compose and there are none so there is a NPE. 

```
Caused by: java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:202)
        at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:198)
        at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:289)
        at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:284)
        at scala.collection.mutable.ArrayOps$ofRef.filterImpl(ArrayOps.scala:198)
        at scala.collection.TraversableLike.filter(TraversableLike.scala:382)
        at scala.collection.TraversableLike.filter$(TraversableLike.scala:382)
        at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:198)
        at com.karumi.shot.Shot.readComposeScreenshotsMetadata(Shot.scala:292)
        at com.karumi.shot.Shot.recordComposeScreenshots(Shot.scala:188)
        at com.karumi.shot.Shot.recordScreenshots(Shot.scala:58)
        at com.karumi.shot.tasks.ExecuteScreenshotTests.executeScreenshotTests(Tasks.scala:73)
```

This is on version 5.5.0

Please let me know if I can provide anymore information to you to get this issue resovled.

**Comment by MrXlebNick** [comment] 2021-01-31 02:59
Same here, also tried 5.4.0 with the same result.

**Comment by AndrewReitz** [comment] 2021-01-31 16:55
I've been able to have the plugin tasks to run and work w/ both 5.5.0 and 5.5.1 but also have received this error on multiple occasions (using the same device so it's not a device discrepancy). It seems to be something with the state of the screenshots, but still haven't been able to pin point it exactly.

**Comment by AndrewReitz** [comment] 2021-02-09 16:50
It appears that this happens if you run executeScreenshotTests and there is nothing in the test directory. 
This is occurring for me when I run `./gradlew executeScreenshotTests -DrunInstrumentation=false` twice in a row. Not sure if that's the only cause, but a more helpful error message would be great.

**Comment by elizavetamikhailova** [comment] 2021-02-17 07:54
I had the same problem and solved it by adding <uses-permission android: name = "android.permission.WRITE_EXTERNAL_STORAGE" /> to my manifest file

**Comment by pedrovgs** [comment] 2021-02-19 07:44
Thanks @elizavetamikhailova! @AndrewReitz @MrXlebNick could you please check if you have the permission in place? It was because you had no tests?

**Comment by MrXlebNick** [comment] 2021-02-20 11:03
@pedrovgs yes, I did have the permission in my manifest from the very beginning

**Comment by pedrovgs** [comment] 2021-03-04 09:40
@MrXlebNick can you check if this is still happening with our latest release? Maybe the issue was related to the device you were using. Our latest release provides support for emulators >= 29.

**Comment by MrXlebNick** [comment] 2021-03-05 13:21
@pedrovgs I just tried with `5.10.0`, but the problem's still there

**Comment by MrXlebNick** [comment] 2021-03-05 17:36
I also tried to choose another emulator (API 28), but it didn't help

**Comment by pedrovgs** [comment] 2021-03-12 08:49
@AndrewReitz @MrXlebNick could you upload a repository reproducing the issue? I've configured shot from scratch in a new project today and it worked for me. A friend of mine also configured it this morning and also worked.

**Comment by cb4d** [comment] 2021-03-12 17:04
I'm seeing the same stack trace as OP, with `5.10.3` when I run `./gradlew devDebugExecuteScreenshotTests -Precord --stacktrace` on an API 27 emulator. I've included the write permission in the `androidTest` manifest

Something I noticed looking at the device file explorer is that the screenshots are successfully being saved to ```/storage/emulated/0/screenshots/com.example.id/screenshots-default```. I also saw in the repo source that `Adb.scala`, `baseStoragePath` is set to `/storage/emulated/0/Download`. Is it possible that this extra path component is causing this?

**Comment by sdoward** [comment] 2021-03-13 17:04
I get this error when updating to `5.9.0`. 

Gradle: `6.8.3`
Task: `./gradlew devDebugExecuteScreenshotTests -Precord --stacktrace`
Emulator: `API 28`

**Comment by AndrewReitz** [comment] 2021-03-13 21:14
> @AndrewReitz @MrXlebNick could you upload a repository reproducing the issue? I've configured shot from scratch in a new project today and it worked for me. A friend of mine also configured it this morning and also worked.

I figured out the issue I was having. https://github.com/Karumi/Shot/issues/188#issuecomment-776080517
Would be nice to get better error messaging around this.

**Comment by pedrovgs** [comment] 2021-03-18 08:45
I'll check what we can do to show some feedback if there are no tests instead of just crashing. What I don't get @tobiasKaminsky is what's going on with your scenario. Are you facing the same NPE? Do you have screenshot tests in your project?

**Comment by sdoward** [comment] 2021-03-18 09:00
I am having this problem and my project has tests

**Comment by pedrovgs** [comment] 2021-03-18 09:42
@sdoward do you have screenshot tests? Could any of you share a project reproducing the issue?

**Comment by tobiasKaminsky** [comment] 2021-03-18 09:44
>  What I don't get @tobiasKaminsky is what's going on with your scenario. Are you facing the same NPE? Do you have screenshot tests in your project?

You can test it if you want:
- git clone git@github.com:nextcloud/android.git
- run: ./gradlew gplayDebugExecuteScreenshotTests -Pscreenshot=true -Pandroid.testInstrumentationRunnerArguments.annotation=com.owncloud.android.utils.ScreenshotTest -Pandroid.testInstrumentationRunnerArguments.class=com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT#showDetailsActivitiesNone
- see that it is working (it might give you a wrong sized screenshot, but at least comparison should work)
- update in build.gradle shot to 5.8.0 or latest 5.10.3
- re-run and see (with --stracktrace):
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gplayDebugExecuteScreenshotTests'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:356)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:202)
        at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:198)
        at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:289)
        at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:284)
        at scala.collection.mutable.ArrayOps$ofRef.filterImpl(ArrayOps.scala:198)
        at scala.collection.TraversableLike.filter(TraversableLike.scala:382)
        at scala.collection.TraversableLike.filter$(TraversableLike.scala:382)
        at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:198)
        at com.karumi.shot.Shot.readScreenshotsMetadata(Shot.scala:264)
        at com.karumi.shot.Shot.verifyScreenshots(Shot.scala:95)
        at com.karumi.shot.tasks.ExecuteScreenshotTests.executeScreenshotTests(Tasks.scala:86)
```

I guess only the second part is important.
It is a bit different from original poster, as I do not use record, but only verify.

**Comment by tobiasKaminsky** [comment] 2021-03-18 09:47
I suspect that 
https://github.com/Karumi/Shot/blob/260f8d5c38f815f6d3f0ef64feb0234aa4375973/core/src/main/scala/com/karumi/shot/Shot.scala#L275
this produces null, as documentation says:
`
public File[] listFiles()
…
If this abstract pathname does not denote a directory, then this method returns null.
…

Which would also fit as 
```
⬇️  Pulling screenshots from your connected devices!
Shot ADB warning: We could not pull screenshots from folder: /sdcard/screenshots/com.nextcloud.client.test/screenshots-compose-default/
Shot ADB warning: rm: /sdcard/screenshots/com.nextcloud.client.test/screenshots-compose-default/: No such file or directory

```
is shown during runtime.

**Comment by sdoward** [comment] 2021-03-18 09:48
@pedrovgs  What do you mean by "screenshotTests"? The plugin requires us to use instrument tests does it? My project has some instrument tests that take screenshots.

Unfortunately I am unable to share the project but I will try to set up a reproducible project

**Comment by tobiasKaminsky** [comment] 2021-03-18 09:54
> Shot ADB warning: We could not pull screenshots from folder: /sdcard/screenshots/com.nextcloud.client.test/screenshots-compose-default/

It seems that this folder is still on emulator:
```
22222   4 -rw-rw---- 1 root sdcard_rw   1340 2021-03-18 10:43 metadata.xml
22221 476 -rw-rw---- 1 root sdcard_rw 484948 2021-03-18 10:43 screenshot_bundle.zip
```

**Comment by aantonic** [comment] 2021-03-25 09:21
I've faced similar issue - running in record mode was successful, but verification fails with NPE.
It turned out that root cause is an issue on my Mac - /tmp folder was not writable so temporal screenshots could not be created. Location of temporal snapshots is defined at https://github.com/Karumi/Shot/blob/260f8d5c38f815f6d3f0ef64feb0234aa4375973/core/src/main/scala/com/karumi/shot/domain/model.scala#L48
I believe.
I've fixed this by making /tmp writable.
As this is not uncommon issue on Mac, I suggest you to consider using some other folder or /var in order to store temporal files.

**Comment by pedrovgs** [comment] 2021-03-30 07:06
@sdoward by screenshot test I mean an instrumentation test taking a screenshot.

**Comment by pedrovgs** [comment] 2021-03-30 07:07
Thanks for the info @tobiasKaminsky now we have a repo reproducing the issue and we can check what's going on 😃

**Comment by pedrovgs** [comment] 2021-03-30 08:57
Ok, I've found what's going on. For those of you facing this exception review your configuration. Once I've analyzed @tobiasKaminsky 's repository I've found the ``ShotTestRunner`` wasn't being configured properly. The part of the project configuration where you need to configure the ``ShotTestRunner``. You can check it out [here](https://github.com/nextcloud/android/pull/8224).

However, I'm going to send a PR improving the feedback when the plugin can't find any metadata file. I've already merged one to improve docs and I'm preparing a new one with some visual feedback for the user.

**Closed** 2021-04-14 10:42 UTC
Labels: bug
