### ISSUE TITLE
Plugin does not add the underlying facebook-screenshot-testing dependency to libraries

### ISSUE THREAD

**Issue by eyalgu** [Karumi/Shot#90] opened 2020-03-04 21:59 UTC
### Expected behaviour
Adding `apply plugin shot` should be all the setup I need when adding snapshot tests to an android library (as oppose to android application)

### Actual behaviour
I need to also add `androidTestImplementation "com.facebook.testing.screenshot:core:0.8.0"`

### Steps to reproduce
create an android library with snapshot and try to access something like `Screenshort.snap`

```
apply plugin: 'com.android.library'
apply plugin: 'shot'

android {
  ...
}

dependencies {
 ...
// androidTestImplementation "com.facebook.testing.screenshot:core:0.8.0" // uncomment to make code compile
}
```

### Version of the library
3.1.0

**Comment by eyalgu** [comment] 2020-03-04 22:03
@digitalbuddha believes this is because `project.getConfigurations` in https://github.com/Karumi/Shot/blob/24ad9f6a46607386e24627a96982f33044ac6d64/shot/src/main/scala/com/karumi/shot/ShotPlugin.scala#L96 does not iterate over libraries.
You will probably need something along the lines of:
```
subprojects { Project project ->
    project.plugins.withId('com.android.library') {
        ...
    }
    project.plugins.withId(''com.android.application'') {
        ...
    }
}
```

**Comment by pedrovgs** [comment] 2020-03-20 15:19
Hi @eyalgu could you please create a project reproducing this error? I've been working on this project the whole day and I couldn't reproduce it by myself.

**Comment by eyalgu** [comment] 2020-03-20 15:48
Sure I'll try to get to it this weekend

**Comment by pedrovgs** [comment] 2020-06-08 08:40
Closing the issue until we have the repository reproducing the error.

**Closed by pedrovgs** 2020-06-08 08:40 UTC
Labels: bug, help wanted
