### ISSUE TITLE
Application suffixes are not being handled correctly when testApplicationId is configured

### ISSUE THREAD

**Issue by fmontesino** [Karumi/Shot#96] opened 2020-04-07 08:39 UTC
### Expected behaviour
If I run `./gradlew <Flavor><BuildType>ExecuteScreenshotTests -Precord` I get all the screenshots recorded and downloaded from the device.

### Actual behaviour
Build fails with this message:

**Execution failed for task ':app:downloadScreenshots'.
Nonzero exit value: 1**

### Steps to reproduce
This is my setup: 
```
buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
 }

productFlavors {
    dev {
        applicationIdSuffix ".dev"
        versionNameSuffix "-dev"
    }
}
```

Setup for Version 4.0.0:
```
shot {
    useComposer = true
}
```

Setup for Version 3.1.0:
```
shot {
    appId = "my.application.package.dev.debug"
    instrumentationTestTask = "testDevDebugComposer"
}
```

It also happens without using composer, by the way.

Attached the whole exception stacktrace
[gradleException.txt](https://github.com/Karumi/Shot/files/4442953/gradleException.txt)

### Version of the library
3.1.0, 4.0.0

**Comment by pedrovgs** [comment] 2020-04-08 07:13
Hi @fmontesino I'm trying to reproduce the error you mentioned but the issue is not related to the appId suffix. Inside the repository ,you can find a folder named ``shot-consumer-flavors``. Inside this folder, an example of an Android app can be found. This app is configured with different flavors and the green flavor uses an application suffix like the one you described. If you execute shot from that repository you should see how it's working. You can run the command ``./gradlew  greenDebugExecuteScreenshotTests`` from the ``shot-consumer-flavors`` directory if you want to try it by yourself.

Could you review your project configuration and ensure you are using Shot 4.0.0, you don't configure any extra parameter for shot and invokes the command ``./gradlew devDebugExecuteScreenshotTests -Precord``? If you still face the issue, please clone this repository and try to run the example project.

Looking at the stacktrace you shared the issue seems to be related to the adb integration and not the usage of the Android Gradle plugin. What operating system are you using? Is the android emulator you are using configured with an SD card?

**Comment by hamorillo** [comment] 2020-04-08 11:12
I don't know if this could help you but I had a similar issue and the stacktrace is almost the same as @fmontesino shared. 

In our project we are using the following configuration on build.gradle:
`defaultConfig {
testApplicationId "es.company.app.test"
}`

This causes that in the device the screenshots were saved under the folder:
`/sdcard/screenshots/es.company.app.test`
and not under the folder that the flavor should have so, when shot is trying to download the screenshot from the incorrect folder. Just removing the previous configuration of the `testApplicationId` everything works fine for me. 

@fmontesino Could be something similar to you?

**Comment by pedrovgs** [comment] 2020-04-08 11:19
You are overriding the ``testApplicationId``? @fmontesino is this something you are also doing in your project?

**Comment by hamorillo** [comment] 2020-04-08 11:24
Exactly, we was overriding the `testApplicationId` and for us this was the problem.

**Comment by pedrovgs** [comment] 2020-04-08 11:27
@hamorillo would you mind if I ask you why you decided to override the app id for the test artifact? I'm also wondering if you could try shot using the latest version and removing the ``testApplicationId`` configuration 😃

**Comment by fmontesino** [comment] 2020-04-08 12:15
Thanks @pedrovgs and @hamorillo for your comments. I can confirm I am not overriding the `testApplicationId` in my gradle file. However, I have the `androidTest/AndroidManifest.xml` with the package set up like `package="my.application.package.test"`. Do you think this has anything to do?

Will try running the example with Shot 4.0.0 👍

**Comment by hamorillo** [comment] 2020-04-08 13:08
> @hamorillo would you mind if I ask you why you decided to override the app id for the test artifact? I'm also wondering if you could try shot using the latest version and removing the `testApplicationId` configuration 😃

@pedrovgs I'm not pretty sure why we were been overriding the appId, I've reviewed the repo and this change was introduced long time ago with another test library, It seems that both were related.

Yesterday, I've updated our app removing the override of `testApplicationId` (now it looks that don't make sense in our code) and using the versión 4.0.0 of shot. It works great!

**Comment by pedrovgs** [comment] 2020-04-08 13:24
Until we can provide support for the usage of the mentioned variable, please remove it if it's possible and use the latest shot release 😃 I'm going to rename the issue so we can fix it soon.

**Comment by fmontesino** [comment] 2020-04-08 14:05
I am not sure the issue is exactly that tbh, I just ran with version 4.0.0 using Composer and two emulators and had the same issue. However, using 3.1.0 apparently works now 😕 

Setup with 4.0.0: 
```
shot {
    useComposer = true
}
```

`/gradlew clean app:devDebugExecuteScreenshotTests -p . -Porchestrator=false -Precord=true`

Output:

> Task :app:devDebugDownloadScreenshots FAILED
⬇️  Pulling screenshots from your connected devices!

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:devDebugDownloadScreenshots'.
> Nonzero exit value: 1

**Comment by pedrovgs** [comment] 2020-04-08 14:40
What did you change in order to get the previous version working? Only the version or did you change anything else?

**Comment by fmontesino** [comment] 2020-04-08 14:54
In 3.1.0 I tried like this with no luck
```
shot {
    appId = "my.application.package.dev.debug"
    instrumentationTestTask = "testDevDebugComposer"
}
```

Changed to not use Composer, it worked!
```
shot {
    appId = "my.application.package.dev.debug"
    instrumentationTestTask = "connectedDevDebugAndroidTest"
}
```

Rolled back to use Composer and it worked 🤔

Tried 4.0.0 with no luck... So I rolled back to 3.1.0 + Composer and apparently it works now 🤷‍♂

**Comment by rlatapy-luna** [comment] 2020-04-17 06:47
@fmontesino Did you add the `sharedUserId` in your manifest ? (the main one, not only the androidTest one)

**Comment by fmontesino** [comment] 2020-04-17 07:42
@rlatapy-luna yes sir! it's working as expected on 3.1.0 so I think it's more of a version problem

**Comment by scm573** [comment] 2020-04-30 05:36
Hey guys. I'm now meeting a similar problem and I think I probably found the cause:

My project puts "applicationIdSuffix" in the buildTypes block but not the productFlavors block.
And due to this process
https://github.com/Karumi/Shot/blob/master/shot/src/main/scala/com/karumi/shot/ShotPlugin.scala#L68
The applicationIdSuffix declared in buildTypes block is not being taken into consideration.
I tried removing that applicationIdSuffix declaration and it becomes working.

Also I commented in another post.
https://github.com/Karumi/Shot/issues/79#issuecomment-621621405

**Comment by fmontesino** [comment] 2020-05-05 14:36
FYI this seems to work properly on 4.1.1 :)

**Comment by fmontesino** [comment] 2020-05-05 18:03
Re-tested with version 4.1.1... Still happening :(

**Comment by pedrovgs** [comment] 2020-05-08 07:00
I'll try to take a look at #100 and #96 today.

**Comment by pedrovgs** [comment] 2020-05-08 12:35
Hi @fmontesino I've just merged a PR fixing this. The suffix was not being used properly for build types but I've just fixed it and I'm about to release a new version with the fix.

**Closed by pedrovgs** 2020-05-08 12:35 UTC
Labels: bug

**Comment by fmontesino** [comment] 2020-05-11 08:08
Will give it a try! Thank you very much!
