### ISSUE TITLE
ExecuteScreenshots fails with exception: Unable to delete file metadata.xml on Windows10 with ADB over WIFI

### ISSUE THREAD

**Issue by lichterschalter** [Karumi/Shot#53] opened 2019-01-15 13:58 UTC
### Expected behaviour
Recording screenshots on Windows 10 with Nexus 4 (Android 5.1.1) connected via ADB over WIFI

### Actual behaviour
The task `gradlew executeScreenshotTests -Precord` takes the screenshots, pulls and saves them and the report, but the process finishes with: 
>`Execution failed for task ':app:executeScreenshotTests'.
   java.io.IOException: Unable to delete file: C: ... \app\screenshots\screenshots-default\metadata.xml`

- The same task works fine on Linux Ubuntu 18.04.1 (Nexus 4, ADB over WIFI)
- The same task works fine using USB connection  (Nexus 4, Win 10)
- The same task works fine with Samsung Galaxy Note 8 (ADB over Wifi, Win 10)

### Steps to reproduce
execute command on **Windows 10** in AndroidStudio Terminal or PowerShell
tested on: **Nexus 4 with android 5.1.1**
targetSdkVersion **28**
minSdkVersion **15**
custom testInstrumentationRunner:
```
public class ScreenshotAndroidJunitRunner extends AndroidJUnitRunner {
    @Override
    public void onCreate(Bundle arguments) {
        ScreenshotRunner.onCreate(this, arguments);
        super.onCreate(arguments);
    }

    @Override
    public void finish(int resultCode, Bundle results) {
        ScreenshotRunner.onDestroy();
        super.finish(resultCode, results);
    }
}
```
shot gradle settings:
```
shot {
    appId = 'myAppId'
    instrumentationTestTask = 'connectedDebugAndroidTest'
    packageTestApkTask = 'packageDebugAndroidTest'
}
```
Test class:
```
@LargeTest
@RunWith(AndroidJUnit4.class)
public class FirstEspressoTest {

    @Rule
    public ActivityTestRule<MainActivity> mActivityRule =
            new ActivityTestRule<>(MainActivity.class);

    @Test
    public void settingsArePresent() throws InterruptedException {
        Thread.sleep(5000);

        //ui interaction
        onView(withId(R.id.action_settings))
                .perform(click());

        //take screenshot
        TakeScreenshotUtil.takeScreenshot("settingsArePresent", mActivityRule.getActivity());

        //check result
        Context targetContext = InstrumentationRegistry.getTargetContext();
        onView(withText(targetContext.getResources().getString(R.string.action_settings)))
                .check(matches(ViewMatchers.isDisplayed()));
    }
}
```
TakeScreenshotUtil class:
```
public class TakeScreenshotUtil {
    public static void takeScreenshot(String name, Activity activity) throws InterruptedException {
        Thread.sleep(2500);
        Log.i("Taking screenshot of ", activity.getLocalClassName() + "(named: " + name + ")");
        InstrumentationRegistry.getInstrumentation().waitForIdleSync();
        Screenshot.snapActivity(activity).record();
    }
}
```
I can not delete the file metadata.xml manually when AndroidStudio is open. I tried to run the command from PowerShell with AndroidStudio closed, but I get the same error.

### Version of the library
shot 2.1.1
with facebooks screenshot testing plugin 0.8.0
with gradle 3.0.0

**Comment by pedrovgs** [comment] 2019-02-26 07:21
Hi @lichterschalter thanks for sending us such a detailed issue. I'm afraid I'd need to make some questions before even thinking in a fix for this issue. Did you check if the metadata file mentioned in the exception exist? Did you check the metadata file permission? Related to this sentence ``I can not delete the file metadata.xml manually when AndroidStudio is open``, could you please clean the project using the commeand ``./gradlew clean`` and then run the tests again using the command ``./gradlew executeScreenshotTests -Precord`` from your terminal? Thank you so much in advance 😃

**Closed** 2020-06-08 08:38 UTC
Labels: bug, help wanted

**Comment by lucianoluzzi** [comment] 2022-02-22 12:17
I'm getting the same issue on Windows 11 when running on an emulator.

Stacktrace below:
```
* What went wrong:
Execution failed for task ':app:debugExecuteScreenshotTests'.
> java.io.IOException: Unable to delete file: C:\Users\lucia\Documents\duco-installer-android\app\screenshots\debug\screenshots-default\metadata_compose.json_emulator-5554
```
The test still runs (and passes) though:
```
> Task :app:debugExecuteScreenshotTests FAILED
?  Comparing screenshots with previous ones.
?  Yeah!!! Your tests are passing.
```

**Comment by badoualy** [comment] 2022-05-07 13:01
Still happening on Windows 10.
As mentionned in the comment above, after killing the OpenJDK process, we can manually delete the file.

The issue is that when the verification test are failing, the html report isn't generated.

@pedrovgs would it be ok for you if we
* wrap the delete in a `try/catch` block to not crash if it can't be deleted? It's not ideal, but not really an issue with an appropriate gitignore rule.
* make the meta filename unique by adding a timestamp or something to prevent the next run to crash because the file already exists.
